"""master

Revision ID: 0f677e4b73fb
Revises: 258bf09f73a7
Create Date: 2025-12-01 15:03:20.050712

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f677e4b73fb'
down_revision: Union[str, None] = '258bf09f73a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    now = datetime.utcnow()
    op.bulk_insert(
        sa.table(
            'users',
            sa.column('id', sa.Integer),
            sa.column('username', sa.String),
            sa.column('email', sa.String),
            sa.column('hashed_password', sa.String),
            sa.column('created_at', sa.DateTime),
            sa.column('updated_at', sa.DateTime),
        ),
        [
            {
                'id': 1,
                'username': 'Test',
                'email': 'test@test.com',
                'hashed_password': '$argon2id$v=19$m=65536,t=3,p=4$8H5PyTmnVGqNESJkbC2ldA$yQiC0thqdq8u9YeVTQg8JIB4RmulXZRZFys3S/3eMaY',
                'created_at': now,
                'updated_at': now,
            },
        ]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
