"""initial

Revision ID: 258bf09f73a7
Revises: 
Create Date: 2025-12-01 14:59:21.761607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '258bf09f73a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('REVENUE', 'EXPENSE', name='accounttype'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_titles_code'), 'account_titles', ['code'], unique=True)
    op.create_index(op.f('ix_account_titles_id'), 'account_titles', ['id'], unique=False)
    op.create_index(op.f('ix_account_titles_type'), 'account_titles', ['type'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_code'), 'regions', ['code'], unique=True)
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_index(op.f('ix_regions_name'), 'regions', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_code'), 'areas', ['code'], unique=True)
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.create_index(op.f('ix_areas_name'), 'areas', ['name'], unique=False)
    op.create_index(op.f('ix_areas_region_id'), 'areas', ['region_id'], unique=False)
    op.create_table('prefectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prefectures_area_id'), 'prefectures', ['area_id'], unique=False)
    op.create_index(op.f('ix_prefectures_code'), 'prefectures', ['code'], unique=True)
    op.create_index(op.f('ix_prefectures_id'), 'prefectures', ['id'], unique=False)
    op.create_index(op.f('ix_prefectures_name'), 'prefectures', ['name'], unique=False)
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.Integer(), nullable=False),
    sa.Column('area', sa.Integer(), nullable=False),
    sa.Column('prefecture', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['prefecture'], ['prefectures.id'], ),
    sa.ForeignKeyConstraint(['region'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_area'), 'shops', ['area'], unique=False)
    op.create_index(op.f('ix_shops_id'), 'shops', ['id'], unique=False)
    op.create_index(op.f('ix_shops_name'), 'shops', ['name'], unique=False)
    op.create_index(op.f('ix_shops_prefecture'), 'shops', ['prefecture'], unique=False)
    op.create_index(op.f('ix_shops_region'), 'shops', ['region'], unique=False)
    op.create_table('shop_account_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('period', sa.Enum('MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'YEARLY', name='accountperiod'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_account_periods_id'), 'shop_account_periods', ['id'], unique=False)
    op.create_index(op.f('ix_shop_account_periods_period'), 'shop_account_periods', ['period'], unique=False)
    op.create_index(op.f('ix_shop_account_periods_shop_id'), 'shop_account_periods', ['shop_id'], unique=False)
    op.create_index(op.f('ix_shop_account_periods_year'), 'shop_account_periods', ['year'], unique=False)
    op.create_table('shop_account_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('account_title_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_title_id'], ['account_titles.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_account_titles_account_title_id'), 'shop_account_titles', ['account_title_id'], unique=False)
    op.create_index(op.f('ix_shop_account_titles_id'), 'shop_account_titles', ['id'], unique=False)
    op.create_index(op.f('ix_shop_account_titles_shop_id'), 'shop_account_titles', ['shop_id'], unique=False)
    op.create_table('shop_account_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('shop_account_period_id', sa.Integer(), nullable=False),
    sa.Column('shop_account_title_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_account_period_id'], ['shop_account_periods.id'], ),
    sa.ForeignKeyConstraint(['shop_account_title_id'], ['shop_account_titles.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_account_settlements_id'), 'shop_account_settlements', ['id'], unique=False)
    op.create_index(op.f('ix_shop_account_settlements_shop_account_period_id'), 'shop_account_settlements', ['shop_account_period_id'], unique=False)
    op.create_index(op.f('ix_shop_account_settlements_shop_account_title_id'), 'shop_account_settlements', ['shop_account_title_id'], unique=False)
    op.create_index(op.f('ix_shop_account_settlements_shop_id'), 'shop_account_settlements', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_account_settlements_shop_id'), table_name='shop_account_settlements')
    op.drop_index(op.f('ix_shop_account_settlements_shop_account_title_id'), table_name='shop_account_settlements')
    op.drop_index(op.f('ix_shop_account_settlements_shop_account_period_id'), table_name='shop_account_settlements')
    op.drop_index(op.f('ix_shop_account_settlements_id'), table_name='shop_account_settlements')
    op.drop_table('shop_account_settlements')
    op.drop_index(op.f('ix_shop_account_titles_shop_id'), table_name='shop_account_titles')
    op.drop_index(op.f('ix_shop_account_titles_id'), table_name='shop_account_titles')
    op.drop_index(op.f('ix_shop_account_titles_account_title_id'), table_name='shop_account_titles')
    op.drop_table('shop_account_titles')
    op.drop_index(op.f('ix_shop_account_periods_year'), table_name='shop_account_periods')
    op.drop_index(op.f('ix_shop_account_periods_shop_id'), table_name='shop_account_periods')
    op.drop_index(op.f('ix_shop_account_periods_period'), table_name='shop_account_periods')
    op.drop_index(op.f('ix_shop_account_periods_id'), table_name='shop_account_periods')
    op.drop_table('shop_account_periods')
    op.drop_index(op.f('ix_shops_region'), table_name='shops')
    op.drop_index(op.f('ix_shops_prefecture'), table_name='shops')
    op.drop_index(op.f('ix_shops_name'), table_name='shops')
    op.drop_index(op.f('ix_shops_id'), table_name='shops')
    op.drop_index(op.f('ix_shops_area'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_prefectures_name'), table_name='prefectures')
    op.drop_index(op.f('ix_prefectures_id'), table_name='prefectures')
    op.drop_index(op.f('ix_prefectures_code'), table_name='prefectures')
    op.drop_index(op.f('ix_prefectures_area_id'), table_name='prefectures')
    op.drop_table('prefectures')
    op.drop_index(op.f('ix_areas_region_id'), table_name='areas')
    op.drop_index(op.f('ix_areas_name'), table_name='areas')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_index(op.f('ix_areas_code'), table_name='areas')
    op.drop_table('areas')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_regions_name'), table_name='regions')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_index(op.f('ix_regions_code'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_account_titles_type'), table_name='account_titles')
    op.drop_index(op.f('ix_account_titles_id'), table_name='account_titles')
    op.drop_index(op.f('ix_account_titles_code'), table_name='account_titles')
    op.drop_table('account_titles')
    # ### end Alembic commands ###
