"""initial

Revision ID: 31c527462177
Revises: 
Create Date: 2025-12-02 20:14:48.676844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31c527462177'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('period_type', sa.Integer(), nullable=False),
    sa.Column('is_cumulative', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_id'), 'shops', ['id'], unique=False)
    op.create_index(op.f('ix_shops_name'), 'shops', ['name'], unique=False)
    op.create_index(op.f('ix_shops_period_type'), 'shops', ['period_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.create_table('shop_account_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('sub_type', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_account_titles_code'), 'shop_account_titles', ['code'], unique=False)
    op.create_index(op.f('ix_shop_account_titles_id'), 'shop_account_titles', ['id'], unique=False)
    op.create_index(op.f('ix_shop_account_titles_shop_id'), 'shop_account_titles', ['shop_id'], unique=False)
    op.create_index(op.f('ix_shop_account_titles_sub_type'), 'shop_account_titles', ['sub_type'], unique=False)
    op.create_index(op.f('ix_shop_account_titles_type'), 'shop_account_titles', ['type'], unique=False)
    op.create_table('shop_account_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('shop_account_title_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_account_title_id'], ['shop_account_titles.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_account_entries_id'), 'shop_account_entries', ['id'], unique=False)
    op.create_index(op.f('ix_shop_account_entries_month'), 'shop_account_entries', ['month'], unique=False)
    op.create_index(op.f('ix_shop_account_entries_shop_account_title_id'), 'shop_account_entries', ['shop_account_title_id'], unique=False)
    op.create_index(op.f('ix_shop_account_entries_shop_id'), 'shop_account_entries', ['shop_id'], unique=False)
    op.create_index(op.f('ix_shop_account_entries_year'), 'shop_account_entries', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_account_entries_year'), table_name='shop_account_entries')
    op.drop_index(op.f('ix_shop_account_entries_shop_id'), table_name='shop_account_entries')
    op.drop_index(op.f('ix_shop_account_entries_shop_account_title_id'), table_name='shop_account_entries')
    op.drop_index(op.f('ix_shop_account_entries_month'), table_name='shop_account_entries')
    op.drop_index(op.f('ix_shop_account_entries_id'), table_name='shop_account_entries')
    op.drop_table('shop_account_entries')
    op.drop_index(op.f('ix_shop_account_titles_type'), table_name='shop_account_titles')
    op.drop_index(op.f('ix_shop_account_titles_sub_type'), table_name='shop_account_titles')
    op.drop_index(op.f('ix_shop_account_titles_shop_id'), table_name='shop_account_titles')
    op.drop_index(op.f('ix_shop_account_titles_id'), table_name='shop_account_titles')
    op.drop_index(op.f('ix_shop_account_titles_code'), table_name='shop_account_titles')
    op.drop_table('shop_account_titles')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shops_period_type'), table_name='shops')
    op.drop_index(op.f('ix_shops_name'), table_name='shops')
    op.drop_index(op.f('ix_shops_id'), table_name='shops')
    op.drop_table('shops')
    # ### end Alembic commands ###
