"""update shop_account_periods

Revision ID: 6381aa53c2f4
Revises: 0f677e4b73fb
Create Date: 2025-12-01 19:19:09.909394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6381aa53c2f4'
down_revision: Union[str, None] = '0f677e4b73fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_account_periods', sa.Column('count_type', sa.Enum('CUMULATIVE', 'NON_CUMULATIVE', name='counttype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_account_periods', 'count_type')
    # ### end Alembic commands ###
