from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    from datetime import datetime

    now = datetime.utcnow()
    op.bulk_insert(
        sa.table(
            'users',
            sa.column('id', sa.Integer),
            sa.column('name', sa.String),
            sa.column('email', sa.String),
            sa.column('hashed_password', sa.String),
            sa.column('created_at', sa.DateTime),
            sa.column('updated_at', sa.DateTime),
        ),
        [
            {
                'id': 1,
                'name': 'テストユーザー',
                'email': 'test@test.com',
                'hashed_password': '$argon2id$v=19$m=65536,t=3,p=4$8H5PyTmnVGqNESJkbC2ldA$yQiC0thqdq8u9YeVTQg8JIB4RmulXZRZFys3S/3eMaY',
                'created_at': now,
                'updated_at': now,
            },
        ],
    )

    op.bulk_insert(
        sa.table(
            'shops',
            sa.column('id', sa.Integer),
            sa.column('name', sa.String),
            sa.column('period_type', sa.Integer),
            sa.column('is_cumulative', sa.Boolean),
            sa.column('created_at', sa.DateTime),
            sa.column('updated_at', sa.DateTime),
        ),
        [
            {
                'id': 1,
                'name': '東京',
                'period_type': 2,
                'is_cumulative': True,
                'created_at': now,
                'updated_at': now,
            },
            {
                'id': 2,
                'name': '大阪',
                'period_type': 2,
                'is_cumulative': False,
                'created_at': now,
                'updated_at': now,
            },
            {
                'id': 1,
                'name': '名古屋',
                'period_type': 3,
                'is_cumulative': True,
                'created_at': now,
                'updated_at': now,
            },
        ],
    )

    op.bulk_insert(
        sa.table(
            'shop_account_titles',
            sa.column('id', sa.Integer),
            sa.column('shop_id', sa.Integer),
            sa.column('type', sa.Integer),
            sa.column('sub_type', sa.Integer),
            sa.column('code', sa.String),
            sa.column('name', sa.String),
            sa.column('order', sa.Integer),
            sa.column('created_at', sa.DateTime),
            sa.column('updated_at', sa.DateTime),
        ),
        [
            {
                "id": 1,
                "shop_id": 1,
                "type": 1,
                "sub_type": 1,
                "code": None,
                "name": "生鮮食品",
                "order": 1,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 2,
                "shop_id": 1,
                "type": 1,
                "sub_type": 1,
                "code": None,
                "name": "加工食品",
                "order": 2,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 3,
                "shop_id": 1,
                "type": 1,
                "sub_type": 1,
                "code": None,
                "name": "菓子",
                "order": 3,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 4,
                "shop_id": 1,
                "type": 1,
                "sub_type": 1,
                "code": None,
                "name": "飲料",
                "order": 4,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 5,
                "shop_id": 1,
                "type": 1,
                "sub_type": 1,
                "code": None,
                "name": "惣菜",
                "order": 5,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 6,
                "shop_id": 1,
                "type": 2,
                "sub_type": 101,
                "code": None,
                "name": "人件費",
                "order": 1,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 7,
                "shop_id": 1,
                "type": 2,
                "sub_type": 101,
                "code": None,
                "name": "水道光熱費",
                "order": 2,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 8,
                "shop_id": 1,
                "type": 2,
                "sub_type": 101,
                "code": None,
                "name": "広告宣伝費",
                "order": 3,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 9,
                "shop_id": 1,
                "type": 2,
                "sub_type": 101,
                "code": None,
                "name": "物流費",
                "order": 4,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 10,
                "shop_id": 1,
                "type": 2,
                "sub_type": 101,
                "code": None,
                "name": "その他経費",
                "order": 5,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 11,
                "shop_id": 2,
                "type": 1,
                "sub_type": 1,
                "code": None,
                "name": "菓子",
                "order": 1,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 12,
                "shop_id": 2,
                "type": 1,
                "sub_type": 1,
                "code": None,
                "name": "飲料",
                "order": 2,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 13,
                "shop_id": 2,
                "type": 1,
                "sub_type": 1,
                "code": None,
                "name": "おもちゃ",
                "order": 3,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 14,
                "shop_id": 2,
                "type": 1,
                "sub_type": 1,
                "code": None,
                "name": "日用品",
                "order": 4,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 15,
                "shop_id": 2,
                "type": 2,
                "sub_type": 101,
                "code": None,
                "name": "人件費",
                "order": 1,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 16,
                "shop_id": 2,
                "type": 2,
                "sub_type": 101,
                "code": None,
                "name": "広告宣伝費",
                "order": 2,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 17,
                "shop_id": 2,
                "type": 2,
                "sub_type": 101,
                "code": None,
                "name": "物流費",
                "order": 3,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 18,
                "shop_id": 2,
                "type": 2,
                "sub_type": 101,
                "code": None,
                "name": "その他経費",
                "order": 4,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 19,
                "shop_id": 2,
                "type": 2,
                "sub_type": 101,
                "code": None,
                "name": "販管費",
                "order": 5,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 20,
                "shop_id": 3,
                "type": 1,
                "sub_type": 1,
                "code": None,
                "name": "生鮮食品",
                "order": 1,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 21,
                "shop_id": 3,
                "type": 1,
                "sub_type": 1,
                "code": None,
                "name": "菓子",
                "order": 2,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 22,
                "shop_id": 3,
                "type": 1,
                "sub_type": 1,
                "code": None,
                "name": "飲料",
                "order": 3,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 23,
                "shop_id": 3,
                "type": 1,
                "sub_type": 1,
                "code": None,
                "name": "惣菜",
                "order": 4,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 24,
                "shop_id": 3,
                "type": 1,
                "sub_type": 1,
                "code": None,
                "name": "日用品",
                "order": 5,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 25,
                "shop_id": 3,
                "type": 2,
                "sub_type": 101,
                "code": None,
                "name": "人件費",
                "order": 1,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 26,
                "shop_id": 3,
                "type": 2,
                "sub_type": 101,
                "code": None,
                "name": "広告宣伝費",
                "order": 2,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 27,
                "shop_id": 3,
                "type": 2,
                "sub_type": 101,
                "code": None,
                "name": "物流費",
                "order": 3,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 28,
                "shop_id": 3,
                "type": 2,
                "sub_type": 101,
                "code": None,
                "name": "その他経費",
                "order": 4,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": 29,
                "shop_id": 3,
                "type": 2,
                "sub_type": 101,
                "code": None,
                "name": "雑費",
                "order": 5,
                "created_at": now,
                "updated_at": now,
            },
        ],
    )

    op.bulk_insert(
        sa.table(
            'shop_account_entries',
            sa.column('id', sa.Integer),
            sa.column('shop_id', sa.Integer),
            sa.column('shop_account_title_id', sa.Integer),
            sa.column('year', sa.Integer),
            sa.column('month', sa.Integer),
            sa.column('amount', sa.DECIMAL),
            sa.column('created_at', sa.DateTime),
            sa.column('updated_at', sa.DateTime),
        ),
        [
            {
                "id": 1,
                "shop_id": 1,
                "shop_account_title_id": 1,
                "year": 2022,
                "month": 3,
                "amount": 3204959.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 2,
                "shop_id": 1,
                "shop_account_title_id": 2,
                "year": 2022,
                "month": 3,
                "amount": 3164166.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 3,
                "shop_id": 1,
                "shop_account_title_id": 3,
                "year": 2022,
                "month": 3,
                "amount": 3261476.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 4,
                "shop_id": 1,
                "shop_account_title_id": 4,
                "year": 2022,
                "month": 3,
                "amount": 3322034.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 5,
                "shop_id": 1,
                "shop_account_title_id": 5,
                "year": 2022,
                "month": 3,
                "amount": 3036327.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 6,
                "shop_id": 1,
                "shop_account_title_id": 1,
                "year": 2022,
                "month": 6,
                "amount": 6566622.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 7,
                "shop_id": 1,
                "shop_account_title_id": 2,
                "year": 2022,
                "month": 6,
                "amount": 6277424.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 8,
                "shop_id": 1,
                "shop_account_title_id": 3,
                "year": 2022,
                "month": 6,
                "amount": 6517662.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 9,
                "shop_id": 1,
                "shop_account_title_id": 4,
                "year": 2022,
                "month": 6,
                "amount": 6388563.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 10,
                "shop_id": 1,
                "shop_account_title_id": 5,
                "year": 2022,
                "month": 6,
                "amount": 6316038.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 11,
                "shop_id": 1,
                "shop_account_title_id": 1,
                "year": 2022,
                "month": 9,
                "amount": 9742787.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 12,
                "shop_id": 1,
                "shop_account_title_id": 2,
                "year": 2022,
                "month": 9,
                "amount": 9758392.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 13,
                "shop_id": 1,
                "shop_account_title_id": 3,
                "year": 2022,
                "month": 9,
                "amount": 9475169.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 14,
                "shop_id": 1,
                "shop_account_title_id": 4,
                "year": 2022,
                "month": 9,
                "amount": 9849131.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 15,
                "shop_id": 1,
                "shop_account_title_id": 5,
                "year": 2022,
                "month": 9,
                "amount": 9622005.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 16,
                "shop_id": 1,
                "shop_account_title_id": 1,
                "year": 2022,
                "month": 12,
                "amount": 12845206.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 17,
                "shop_id": 1,
                "shop_account_title_id": 2,
                "year": 2022,
                "month": 12,
                "amount": 12792169.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 18,
                "shop_id": 1,
                "shop_account_title_id": 3,
                "year": 2022,
                "month": 12,
                "amount": 12695399.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 19,
                "shop_id": 1,
                "shop_account_title_id": 4,
                "year": 2022,
                "month": 12,
                "amount": 12779348.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 20,
                "shop_id": 1,
                "shop_account_title_id": 5,
                "year": 2022,
                "month": 12,
                "amount": 12701888.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 21,
                "shop_id": 1,
                "shop_account_title_id": 1,
                "year": 2023,
                "month": 3,
                "amount": 3289948.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 22,
                "shop_id": 1,
                "shop_account_title_id": 2,
                "year": 2023,
                "month": 3,
                "amount": 3109373.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 23,
                "shop_id": 1,
                "shop_account_title_id": 3,
                "year": 2023,
                "month": 3,
                "amount": 2857033.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 24,
                "shop_id": 1,
                "shop_account_title_id": 4,
                "year": 2023,
                "month": 3,
                "amount": 3241988.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 25,
                "shop_id": 1,
                "shop_account_title_id": 5,
                "year": 2023,
                "month": 3,
                "amount": 3151893.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 26,
                "shop_id": 1,
                "shop_account_title_id": 1,
                "year": 2023,
                "month": 6,
                "amount": 6447561.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 27,
                "shop_id": 1,
                "shop_account_title_id": 2,
                "year": 2023,
                "month": 6,
                "amount": 6293548.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 28,
                "shop_id": 1,
                "shop_account_title_id": 3,
                "year": 2023,
                "month": 6,
                "amount": 6343029.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 29,
                "shop_id": 1,
                "shop_account_title_id": 4,
                "year": 2023,
                "month": 6,
                "amount": 6205542.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 30,
                "shop_id": 1,
                "shop_account_title_id": 5,
                "year": 2023,
                "month": 6,
                "amount": 6252876.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 31,
                "shop_id": 1,
                "shop_account_title_id": 1,
                "year": 2023,
                "month": 9,
                "amount": 9749984.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 32,
                "shop_id": 1,
                "shop_account_title_id": 2,
                "year": 2023,
                "month": 9,
                "amount": 9635533.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 33,
                "shop_id": 1,
                "shop_account_title_id": 3,
                "year": 2023,
                "month": 9,
                "amount": 9492534.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 34,
                "shop_id": 1,
                "shop_account_title_id": 4,
                "year": 2023,
                "month": 9,
                "amount": 9404242.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 35,
                "shop_id": 1,
                "shop_account_title_id": 5,
                "year": 2023,
                "month": 9,
                "amount": 9287522.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 36,
                "shop_id": 1,
                "shop_account_title_id": 1,
                "year": 2023,
                "month": 12,
                "amount": 13006730.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 37,
                "shop_id": 1,
                "shop_account_title_id": 2,
                "year": 2023,
                "month": 12,
                "amount": 12860053.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 38,
                "shop_id": 1,
                "shop_account_title_id": 3,
                "year": 2023,
                "month": 12,
                "amount": 12626353.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 39,
                "shop_id": 1,
                "shop_account_title_id": 4,
                "year": 2023,
                "month": 12,
                "amount": 12787126.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 40,
                "shop_id": 1,
                "shop_account_title_id": 5,
                "year": 2023,
                "month": 12,
                "amount": 12626281.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 41,
                "shop_id": 1,
                "shop_account_title_id": 1,
                "year": 2024,
                "month": 3,
                "amount": 3349729.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 42,
                "shop_id": 1,
                "shop_account_title_id": 2,
                "year": 2024,
                "month": 3,
                "amount": 3406379.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 43,
                "shop_id": 1,
                "shop_account_title_id": 3,
                "year": 2024,
                "month": 3,
                "amount": 3091084.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 44,
                "shop_id": 1,
                "shop_account_title_id": 4,
                "year": 2024,
                "month": 3,
                "amount": 3290792.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 45,
                "shop_id": 1,
                "shop_account_title_id": 5,
                "year": 2024,
                "month": 3,
                "amount": 3236007.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 46,
                "shop_id": 1,
                "shop_account_title_id": 1,
                "year": 2024,
                "month": 6,
                "amount": 6369905.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 47,
                "shop_id": 1,
                "shop_account_title_id": 2,
                "year": 2024,
                "month": 6,
                "amount": 6526462.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 48,
                "shop_id": 1,
                "shop_account_title_id": 3,
                "year": 2024,
                "month": 6,
                "amount": 6250403.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 49,
                "shop_id": 1,
                "shop_account_title_id": 4,
                "year": 2024,
                "month": 6,
                "amount": 6443415.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 50,
                "shop_id": 1,
                "shop_account_title_id": 5,
                "year": 2024,
                "month": 6,
                "amount": 6274328.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 51,
                "shop_id": 1,
                "shop_account_title_id": 1,
                "year": 2024,
                "month": 9,
                "amount": 9353644.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 52,
                "shop_id": 1,
                "shop_account_title_id": 2,
                "year": 2024,
                "month": 9,
                "amount": 9640212.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 53,
                "shop_id": 1,
                "shop_account_title_id": 3,
                "year": 2024,
                "month": 9,
                "amount": 9450465.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 54,
                "shop_id": 1,
                "shop_account_title_id": 4,
                "year": 2024,
                "month": 9,
                "amount": 9610651.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 55,
                "shop_id": 1,
                "shop_account_title_id": 5,
                "year": 2024,
                "month": 9,
                "amount": 9415457.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 56,
                "shop_id": 1,
                "shop_account_title_id": 1,
                "year": 2024,
                "month": 12,
                "amount": 12602694.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 57,
                "shop_id": 1,
                "shop_account_title_id": 2,
                "year": 2024,
                "month": 12,
                "amount": 12995270.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 58,
                "shop_id": 1,
                "shop_account_title_id": 3,
                "year": 2024,
                "month": 12,
                "amount": 12262153.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 59,
                "shop_id": 1,
                "shop_account_title_id": 4,
                "year": 2024,
                "month": 12,
                "amount": 12891531.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 60,
                "shop_id": 1,
                "shop_account_title_id": 5,
                "year": 2024,
                "month": 12,
                "amount": 12476404.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 61,
                "shop_id": 1,
                "shop_account_title_id": 6,
                "year": 2022,
                "month": 3,
                "amount": 838073.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 62,
                "shop_id": 1,
                "shop_account_title_id": 7,
                "year": 2022,
                "month": 3,
                "amount": 792061.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 63,
                "shop_id": 1,
                "shop_account_title_id": 8,
                "year": 2022,
                "month": 3,
                "amount": 867623.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 64,
                "shop_id": 1,
                "shop_account_title_id": 9,
                "year": 2022,
                "month": 3,
                "amount": 831596.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 65,
                "shop_id": 1,
                "shop_account_title_id": 10,
                "year": 2022,
                "month": 3,
                "amount": 800123.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 66,
                "shop_id": 1,
                "shop_account_title_id": 6,
                "year": 2022,
                "month": 6,
                "amount": 1666021.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 67,
                "shop_id": 1,
                "shop_account_title_id": 7,
                "year": 2022,
                "month": 6,
                "amount": 1600945.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 68,
                "shop_id": 1,
                "shop_account_title_id": 8,
                "year": 2022,
                "month": 6,
                "amount": 1713727.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 69,
                "shop_id": 1,
                "shop_account_title_id": 9,
                "year": 2022,
                "month": 6,
                "amount": 1671509.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 70,
                "shop_id": 1,
                "shop_account_title_id": 10,
                "year": 2022,
                "month": 6,
                "amount": 1641009.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 71,
                "shop_id": 1,
                "shop_account_title_id": 6,
                "year": 2022,
                "month": 9,
                "amount": 2499364.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 72,
                "shop_id": 1,
                "shop_account_title_id": 7,
                "year": 2022,
                "month": 9,
                "amount": 2444794.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 73,
                "shop_id": 1,
                "shop_account_title_id": 8,
                "year": 2022,
                "month": 9,
                "amount": 2548187.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 74,
                "shop_id": 1,
                "shop_account_title_id": 9,
                "year": 2022,
                "month": 9,
                "amount": 2491550.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 75,
                "shop_id": 1,
                "shop_account_title_id": 10,
                "year": 2022,
                "month": 9,
                "amount": 2444023.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 76,
                "shop_id": 1,
                "shop_account_title_id": 6,
                "year": 2022,
                "month": 12,
                "amount": 3305653.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 77,
                "shop_id": 1,
                "shop_account_title_id": 7,
                "year": 2022,
                "month": 12,
                "amount": 3313565.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 78,
                "shop_id": 1,
                "shop_account_title_id": 8,
                "year": 2022,
                "month": 12,
                "amount": 3373357.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 79,
                "shop_id": 1,
                "shop_account_title_id": 9,
                "year": 2022,
                "month": 12,
                "amount": 3315405.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 80,
                "shop_id": 1,
                "shop_account_title_id": 10,
                "year": 2022,
                "month": 12,
                "amount": 3296927.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 81,
                "shop_id": 1,
                "shop_account_title_id": 6,
                "year": 2023,
                "month": 3,
                "amount": 753203.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 82,
                "shop_id": 1,
                "shop_account_title_id": 7,
                "year": 2023,
                "month": 3,
                "amount": 826414.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 83,
                "shop_id": 1,
                "shop_account_title_id": 8,
                "year": 2023,
                "month": 3,
                "amount": 836609.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 84,
                "shop_id": 1,
                "shop_account_title_id": 9,
                "year": 2023,
                "month": 3,
                "amount": 838762.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 85,
                "shop_id": 1,
                "shop_account_title_id": 10,
                "year": 2023,
                "month": 3,
                "amount": 790941.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 86,
                "shop_id": 1,
                "shop_account_title_id": 6,
                "year": 2023,
                "month": 6,
                "amount": 1608767.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 87,
                "shop_id": 1,
                "shop_account_title_id": 7,
                "year": 2023,
                "month": 6,
                "amount": 1665027.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 88,
                "shop_id": 1,
                "shop_account_title_id": 8,
                "year": 2023,
                "month": 6,
                "amount": 1611788.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 89,
                "shop_id": 1,
                "shop_account_title_id": 9,
                "year": 2023,
                "month": 6,
                "amount": 1641899.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 90,
                "shop_id": 1,
                "shop_account_title_id": 10,
                "year": 2023,
                "month": 6,
                "amount": 1605673.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 91,
                "shop_id": 1,
                "shop_account_title_id": 6,
                "year": 2023,
                "month": 9,
                "amount": 2385775.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 92,
                "shop_id": 1,
                "shop_account_title_id": 7,
                "year": 2023,
                "month": 9,
                "amount": 2472951.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 93,
                "shop_id": 1,
                "shop_account_title_id": 8,
                "year": 2023,
                "month": 9,
                "amount": 2447087.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 94,
                "shop_id": 1,
                "shop_account_title_id": 9,
                "year": 2023,
                "month": 9,
                "amount": 2479608.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 95,
                "shop_id": 1,
                "shop_account_title_id": 10,
                "year": 2023,
                "month": 9,
                "amount": 2476345.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 96,
                "shop_id": 1,
                "shop_account_title_id": 6,
                "year": 2023,
                "month": 12,
                "amount": 3238716.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 97,
                "shop_id": 1,
                "shop_account_title_id": 7,
                "year": 2023,
                "month": 12,
                "amount": 3324700.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 98,
                "shop_id": 1,
                "shop_account_title_id": 8,
                "year": 2023,
                "month": 12,
                "amount": 3240510.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 99,
                "shop_id": 1,
                "shop_account_title_id": 9,
                "year": 2023,
                "month": 12,
                "amount": 3273806.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 100,
                "shop_id": 1,
                "shop_account_title_id": 10,
                "year": 2023,
                "month": 12,
                "amount": 3321918.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 101,
                "shop_id": 1,
                "shop_account_title_id": 6,
                "year": 2024,
                "month": 3,
                "amount": 800548.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 102,
                "shop_id": 1,
                "shop_account_title_id": 7,
                "year": 2024,
                "month": 3,
                "amount": 850715.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 103,
                "shop_id": 1,
                "shop_account_title_id": 8,
                "year": 2024,
                "month": 3,
                "amount": 816636.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 104,
                "shop_id": 1,
                "shop_account_title_id": 9,
                "year": 2024,
                "month": 3,
                "amount": 790040.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 105,
                "shop_id": 1,
                "shop_account_title_id": 10,
                "year": 2024,
                "month": 3,
                "amount": 840508.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 106,
                "shop_id": 1,
                "shop_account_title_id": 6,
                "year": 2024,
                "month": 6,
                "amount": 1635537.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 107,
                "shop_id": 1,
                "shop_account_title_id": 7,
                "year": 2024,
                "month": 6,
                "amount": 1612523.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 108,
                "shop_id": 1,
                "shop_account_title_id": 8,
                "year": 2024,
                "month": 6,
                "amount": 1658010.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 109,
                "shop_id": 1,
                "shop_account_title_id": 9,
                "year": 2024,
                "month": 6,
                "amount": 1514670.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 110,
                "shop_id": 1,
                "shop_account_title_id": 10,
                "year": 2024,
                "month": 6,
                "amount": 1697910.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 111,
                "shop_id": 1,
                "shop_account_title_id": 6,
                "year": 2024,
                "month": 9,
                "amount": 2458866.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 112,
                "shop_id": 1,
                "shop_account_title_id": 7,
                "year": 2024,
                "month": 9,
                "amount": 2451456.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 113,
                "shop_id": 1,
                "shop_account_title_id": 8,
                "year": 2024,
                "month": 9,
                "amount": 2463229.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 114,
                "shop_id": 1,
                "shop_account_title_id": 9,
                "year": 2024,
                "month": 9,
                "amount": 2371245.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 115,
                "shop_id": 1,
                "shop_account_title_id": 10,
                "year": 2024,
                "month": 9,
                "amount": 2503224.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 116,
                "shop_id": 1,
                "shop_account_title_id": 6,
                "year": 2024,
                "month": 12,
                "amount": 3314736.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 117,
                "shop_id": 1,
                "shop_account_title_id": 7,
                "year": 2024,
                "month": 12,
                "amount": 3273009.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 118,
                "shop_id": 1,
                "shop_account_title_id": 8,
                "year": 2024,
                "month": 12,
                "amount": 3249683.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 119,
                "shop_id": 1,
                "shop_account_title_id": 9,
                "year": 2024,
                "month": 12,
                "amount": 3260241.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 120,
                "shop_id": 1,
                "shop_account_title_id": 10,
                "year": 2024,
                "month": 12,
                "amount": 3325808.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 121,
                "shop_id": 2,
                "shop_account_title_id": 11,
                "year": 2022,
                "month": 3,
                "amount": 1176494.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 122,
                "shop_id": 2,
                "shop_account_title_id": 12,
                "year": 2022,
                "month": 3,
                "amount": 1109530.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 123,
                "shop_id": 2,
                "shop_account_title_id": 13,
                "year": 2022,
                "month": 3,
                "amount": 1045043.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 124,
                "shop_id": 2,
                "shop_account_title_id": 14,
                "year": 2022,
                "month": 3,
                "amount": 1200376.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 125,
                "shop_id": 2,
                "shop_account_title_id": 11,
                "year": 2022,
                "month": 6,
                "amount": 1011344.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 126,
                "shop_id": 2,
                "shop_account_title_id": 12,
                "year": 2022,
                "month": 6,
                "amount": 1090252.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 127,
                "shop_id": 2,
                "shop_account_title_id": 13,
                "year": 2022,
                "month": 6,
                "amount": 1084446.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 128,
                "shop_id": 2,
                "shop_account_title_id": 14,
                "year": 2022,
                "month": 6,
                "amount": 967987.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 129,
                "shop_id": 2,
                "shop_account_title_id": 11,
                "year": 2022,
                "month": 9,
                "amount": 1024692.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 130,
                "shop_id": 2,
                "shop_account_title_id": 12,
                "year": 2022,
                "month": 9,
                "amount": 1009987.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 131,
                "shop_id": 2,
                "shop_account_title_id": 13,
                "year": 2022,
                "month": 9,
                "amount": 1028860.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 132,
                "shop_id": 2,
                "shop_account_title_id": 14,
                "year": 2022,
                "month": 9,
                "amount": 1098343.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 133,
                "shop_id": 2,
                "shop_account_title_id": 11,
                "year": 2022,
                "month": 12,
                "amount": 1125960.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 134,
                "shop_id": 2,
                "shop_account_title_id": 12,
                "year": 2022,
                "month": 12,
                "amount": 1004080.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 135,
                "shop_id": 2,
                "shop_account_title_id": 13,
                "year": 2022,
                "month": 12,
                "amount": 1083707.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 136,
                "shop_id": 2,
                "shop_account_title_id": 14,
                "year": 2022,
                "month": 12,
                "amount": 1048320.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 137,
                "shop_id": 2,
                "shop_account_title_id": 11,
                "year": 2023,
                "month": 3,
                "amount": 933154.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 138,
                "shop_id": 2,
                "shop_account_title_id": 12,
                "year": 2023,
                "month": 3,
                "amount": 1107631.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 139,
                "shop_id": 2,
                "shop_account_title_id": 13,
                "year": 2023,
                "month": 3,
                "amount": 992899.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 140,
                "shop_id": 2,
                "shop_account_title_id": 14,
                "year": 2023,
                "month": 3,
                "amount": 964797.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 141,
                "shop_id": 2,
                "shop_account_title_id": 11,
                "year": 2023,
                "month": 6,
                "amount": 1037337.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 142,
                "shop_id": 2,
                "shop_account_title_id": 12,
                "year": 2023,
                "month": 6,
                "amount": 1062836.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 143,
                "shop_id": 2,
                "shop_account_title_id": 13,
                "year": 2023,
                "month": 6,
                "amount": 1066685.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 144,
                "shop_id": 2,
                "shop_account_title_id": 14,
                "year": 2023,
                "month": 6,
                "amount": 1118600.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 145,
                "shop_id": 2,
                "shop_account_title_id": 11,
                "year": 2023,
                "month": 9,
                "amount": 1001043.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 146,
                "shop_id": 2,
                "shop_account_title_id": 12,
                "year": 2023,
                "month": 9,
                "amount": 1111000.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 147,
                "shop_id": 2,
                "shop_account_title_id": 13,
                "year": 2023,
                "month": 9,
                "amount": 1103376.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 148,
                "shop_id": 2,
                "shop_account_title_id": 14,
                "year": 2023,
                "month": 9,
                "amount": 1186486.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 149,
                "shop_id": 2,
                "shop_account_title_id": 11,
                "year": 2023,
                "month": 12,
                "amount": 967560.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 150,
                "shop_id": 2,
                "shop_account_title_id": 12,
                "year": 2023,
                "month": 12,
                "amount": 1108528.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 151,
                "shop_id": 2,
                "shop_account_title_id": 13,
                "year": 2023,
                "month": 12,
                "amount": 1059819.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 152,
                "shop_id": 2,
                "shop_account_title_id": 14,
                "year": 2023,
                "month": 12,
                "amount": 1174669.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 153,
                "shop_id": 2,
                "shop_account_title_id": 11,
                "year": 2024,
                "month": 3,
                "amount": 1041820.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 154,
                "shop_id": 2,
                "shop_account_title_id": 12,
                "year": 2024,
                "month": 3,
                "amount": 1098891.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 155,
                "shop_id": 2,
                "shop_account_title_id": 13,
                "year": 2024,
                "month": 3,
                "amount": 992326.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 156,
                "shop_id": 2,
                "shop_account_title_id": 14,
                "year": 2024,
                "month": 3,
                "amount": 974856.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 157,
                "shop_id": 2,
                "shop_account_title_id": 11,
                "year": 2024,
                "month": 6,
                "amount": 1040990.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 158,
                "shop_id": 2,
                "shop_account_title_id": 12,
                "year": 2024,
                "month": 6,
                "amount": 997190.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 159,
                "shop_id": 2,
                "shop_account_title_id": 13,
                "year": 2024,
                "month": 6,
                "amount": 1190781.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 160,
                "shop_id": 2,
                "shop_account_title_id": 14,
                "year": 2024,
                "month": 6,
                "amount": 969989.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 161,
                "shop_id": 2,
                "shop_account_title_id": 11,
                "year": 2024,
                "month": 9,
                "amount": 1024188.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 162,
                "shop_id": 2,
                "shop_account_title_id": 12,
                "year": 2024,
                "month": 9,
                "amount": 1049766.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 163,
                "shop_id": 2,
                "shop_account_title_id": 13,
                "year": 2024,
                "month": 9,
                "amount": 989218.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 164,
                "shop_id": 2,
                "shop_account_title_id": 14,
                "year": 2024,
                "month": 9,
                "amount": 1165326.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 165,
                "shop_id": 2,
                "shop_account_title_id": 11,
                "year": 2024,
                "month": 12,
                "amount": 1197323.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 166,
                "shop_id": 2,
                "shop_account_title_id": 12,
                "year": 2024,
                "month": 12,
                "amount": 1229158.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 167,
                "shop_id": 2,
                "shop_account_title_id": 13,
                "year": 2024,
                "month": 12,
                "amount": 1192334.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 168,
                "shop_id": 2,
                "shop_account_title_id": 14,
                "year": 2024,
                "month": 12,
                "amount": 1049212.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 169,
                "shop_id": 2,
                "shop_account_title_id": 15,
                "year": 2022,
                "month": 3,
                "amount": 244267.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 170,
                "shop_id": 2,
                "shop_account_title_id": 16,
                "year": 2022,
                "month": 3,
                "amount": 276592.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 171,
                "shop_id": 2,
                "shop_account_title_id": 17,
                "year": 2022,
                "month": 3,
                "amount": 300244.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 172,
                "shop_id": 2,
                "shop_account_title_id": 18,
                "year": 2022,
                "month": 3,
                "amount": 297835.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 173,
                "shop_id": 2,
                "shop_account_title_id": 19,
                "year": 2022,
                "month": 3,
                "amount": 272315.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 174,
                "shop_id": 2,
                "shop_account_title_id": 15,
                "year": 2022,
                "month": 6,
                "amount": 260047.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 175,
                "shop_id": 2,
                "shop_account_title_id": 16,
                "year": 2022,
                "month": 6,
                "amount": 269961.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 176,
                "shop_id": 2,
                "shop_account_title_id": 17,
                "year": 2022,
                "month": 6,
                "amount": 273644.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 177,
                "shop_id": 2,
                "shop_account_title_id": 18,
                "year": 2022,
                "month": 6,
                "amount": 295860.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 178,
                "shop_id": 2,
                "shop_account_title_id": 19,
                "year": 2022,
                "month": 6,
                "amount": 266786.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 179,
                "shop_id": 2,
                "shop_account_title_id": 15,
                "year": 2022,
                "month": 9,
                "amount": 269918.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 180,
                "shop_id": 2,
                "shop_account_title_id": 16,
                "year": 2022,
                "month": 9,
                "amount": 245674.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 181,
                "shop_id": 2,
                "shop_account_title_id": 17,
                "year": 2022,
                "month": 9,
                "amount": 261886.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 182,
                "shop_id": 2,
                "shop_account_title_id": 18,
                "year": 2022,
                "month": 9,
                "amount": 291914.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 183,
                "shop_id": 2,
                "shop_account_title_id": 19,
                "year": 2022,
                "month": 9,
                "amount": 255399.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 184,
                "shop_id": 2,
                "shop_account_title_id": 15,
                "year": 2022,
                "month": 12,
                "amount": 292278.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 185,
                "shop_id": 2,
                "shop_account_title_id": 16,
                "year": 2022,
                "month": 12,
                "amount": 239815.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 186,
                "shop_id": 2,
                "shop_account_title_id": 17,
                "year": 2022,
                "month": 12,
                "amount": 300571.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 187,
                "shop_id": 2,
                "shop_account_title_id": 18,
                "year": 2022,
                "month": 12,
                "amount": 235532.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 188,
                "shop_id": 2,
                "shop_account_title_id": 19,
                "year": 2022,
                "month": 12,
                "amount": 262251.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 189,
                "shop_id": 2,
                "shop_account_title_id": 15,
                "year": 2023,
                "month": 3,
                "amount": 273869.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 190,
                "shop_id": 2,
                "shop_account_title_id": 16,
                "year": 2023,
                "month": 3,
                "amount": 297021.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 191,
                "shop_id": 2,
                "shop_account_title_id": 17,
                "year": 2023,
                "month": 3,
                "amount": 285605.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 192,
                "shop_id": 2,
                "shop_account_title_id": 18,
                "year": 2023,
                "month": 3,
                "amount": 282796.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 193,
                "shop_id": 2,
                "shop_account_title_id": 19,
                "year": 2023,
                "month": 3,
                "amount": 245974.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 194,
                "shop_id": 2,
                "shop_account_title_id": 15,
                "year": 2023,
                "month": 6,
                "amount": 288131.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 195,
                "shop_id": 2,
                "shop_account_title_id": 16,
                "year": 2023,
                "month": 6,
                "amount": 262472.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 196,
                "shop_id": 2,
                "shop_account_title_id": 17,
                "year": 2023,
                "month": 6,
                "amount": 258601.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 197,
                "shop_id": 2,
                "shop_account_title_id": 18,
                "year": 2023,
                "month": 6,
                "amount": 314848.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 198,
                "shop_id": 2,
                "shop_account_title_id": 19,
                "year": 2023,
                "month": 6,
                "amount": 267859.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 199,
                "shop_id": 2,
                "shop_account_title_id": 15,
                "year": 2023,
                "month": 9,
                "amount": 238755.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 200,
                "shop_id": 2,
                "shop_account_title_id": 16,
                "year": 2023,
                "month": 9,
                "amount": 289489.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 201,
                "shop_id": 2,
                "shop_account_title_id": 17,
                "year": 2023,
                "month": 9,
                "amount": 275721.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 202,
                "shop_id": 2,
                "shop_account_title_id": 18,
                "year": 2023,
                "month": 9,
                "amount": 294864.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 203,
                "shop_id": 2,
                "shop_account_title_id": 19,
                "year": 2023,
                "month": 9,
                "amount": 301375.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 204,
                "shop_id": 2,
                "shop_account_title_id": 15,
                "year": 2023,
                "month": 12,
                "amount": 252276.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 205,
                "shop_id": 2,
                "shop_account_title_id": 16,
                "year": 2023,
                "month": 12,
                "amount": 306708.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 206,
                "shop_id": 2,
                "shop_account_title_id": 17,
                "year": 2023,
                "month": 12,
                "amount": 245755.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 207,
                "shop_id": 2,
                "shop_account_title_id": 18,
                "year": 2023,
                "month": 12,
                "amount": 279920.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 208,
                "shop_id": 2,
                "shop_account_title_id": 19,
                "year": 2023,
                "month": 12,
                "amount": 279745.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 209,
                "shop_id": 2,
                "shop_account_title_id": 15,
                "year": 2024,
                "month": 3,
                "amount": 272075.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 210,
                "shop_id": 2,
                "shop_account_title_id": 16,
                "year": 2024,
                "month": 3,
                "amount": 284569.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 211,
                "shop_id": 2,
                "shop_account_title_id": 17,
                "year": 2024,
                "month": 3,
                "amount": 288317.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 212,
                "shop_id": 2,
                "shop_account_title_id": 18,
                "year": 2024,
                "month": 3,
                "amount": 299540.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 213,
                "shop_id": 2,
                "shop_account_title_id": 19,
                "year": 2024,
                "month": 3,
                "amount": 281798.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 214,
                "shop_id": 2,
                "shop_account_title_id": 15,
                "year": 2024,
                "month": 6,
                "amount": 246165.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 215,
                "shop_id": 2,
                "shop_account_title_id": 16,
                "year": 2024,
                "month": 6,
                "amount": 270937.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 216,
                "shop_id": 2,
                "shop_account_title_id": 17,
                "year": 2024,
                "month": 6,
                "amount": 274630.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 217,
                "shop_id": 2,
                "shop_account_title_id": 18,
                "year": 2024,
                "month": 6,
                "amount": 265409.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 218,
                "shop_id": 2,
                "shop_account_title_id": 19,
                "year": 2024,
                "month": 6,
                "amount": 280938.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 219,
                "shop_id": 2,
                "shop_account_title_id": 15,
                "year": 2024,
                "month": 9,
                "amount": 243576.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 220,
                "shop_id": 2,
                "shop_account_title_id": 16,
                "year": 2024,
                "month": 9,
                "amount": 222243.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 221,
                "shop_id": 2,
                "shop_account_title_id": 17,
                "year": 2024,
                "month": 9,
                "amount": 227105.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 222,
                "shop_id": 2,
                "shop_account_title_id": 18,
                "year": 2024,
                "month": 9,
                "amount": 260479.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 223,
                "shop_id": 2,
                "shop_account_title_id": 19,
                "year": 2024,
                "month": 9,
                "amount": 301131.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 224,
                "shop_id": 2,
                "shop_account_title_id": 15,
                "year": 2024,
                "month": 12,
                "amount": 273470.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 225,
                "shop_id": 2,
                "shop_account_title_id": 16,
                "year": 2024,
                "month": 12,
                "amount": 290643.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 226,
                "shop_id": 2,
                "shop_account_title_id": 17,
                "year": 2024,
                "month": 12,
                "amount": 321929.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 227,
                "shop_id": 2,
                "shop_account_title_id": 18,
                "year": 2024,
                "month": 12,
                "amount": 304928.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 228,
                "shop_id": 2,
                "shop_account_title_id": 19,
                "year": 2024,
                "month": 12,
                "amount": 269945.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 229,
                "shop_id": 3,
                "shop_account_title_id": 20,
                "year": 2022,
                "month": 6,
                "amount": 6082384.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 230,
                "shop_id": 3,
                "shop_account_title_id": 21,
                "year": 2022,
                "month": 6,
                "amount": 6236744.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 231,
                "shop_id": 3,
                "shop_account_title_id": 22,
                "year": 2022,
                "month": 6,
                "amount": 6150398.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 232,
                "shop_id": 3,
                "shop_account_title_id": 23,
                "year": 2022,
                "month": 6,
                "amount": 6597950.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 233,
                "shop_id": 3,
                "shop_account_title_id": 24,
                "year": 2022,
                "month": 6,
                "amount": 6587610.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 234,
                "shop_id": 3,
                "shop_account_title_id": 20,
                "year": 2022,
                "month": 12,
                "amount": 12368527.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 235,
                "shop_id": 3,
                "shop_account_title_id": 21,
                "year": 2022,
                "month": 12,
                "amount": 12572149.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 236,
                "shop_id": 3,
                "shop_account_title_id": 22,
                "year": 2022,
                "month": 12,
                "amount": 12487508.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 237,
                "shop_id": 3,
                "shop_account_title_id": 23,
                "year": 2022,
                "month": 12,
                "amount": 13076639.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 238,
                "shop_id": 3,
                "shop_account_title_id": 24,
                "year": 2022,
                "month": 12,
                "amount": 13105382.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 239,
                "shop_id": 3,
                "shop_account_title_id": 20,
                "year": 2023,
                "month": 6,
                "amount": 6235380.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 240,
                "shop_id": 3,
                "shop_account_title_id": 21,
                "year": 2023,
                "month": 6,
                "amount": 6573686.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 241,
                "shop_id": 3,
                "shop_account_title_id": 22,
                "year": 2023,
                "month": 6,
                "amount": 6682586.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 242,
                "shop_id": 3,
                "shop_account_title_id": 23,
                "year": 2023,
                "month": 6,
                "amount": 6454387.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 243,
                "shop_id": 3,
                "shop_account_title_id": 24,
                "year": 2023,
                "month": 6,
                "amount": 6393186.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 244,
                "shop_id": 3,
                "shop_account_title_id": 20,
                "year": 2023,
                "month": 12,
                "amount": 12296516.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 245,
                "shop_id": 3,
                "shop_account_title_id": 21,
                "year": 2023,
                "month": 12,
                "amount": 12768792.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 246,
                "shop_id": 3,
                "shop_account_title_id": 22,
                "year": 2023,
                "month": 12,
                "amount": 13286389.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 247,
                "shop_id": 3,
                "shop_account_title_id": 23,
                "year": 2023,
                "month": 12,
                "amount": 12754278.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 248,
                "shop_id": 3,
                "shop_account_title_id": 24,
                "year": 2023,
                "month": 12,
                "amount": 12646459.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 249,
                "shop_id": 3,
                "shop_account_title_id": 20,
                "year": 2024,
                "month": 6,
                "amount": 6527741.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 250,
                "shop_id": 3,
                "shop_account_title_id": 21,
                "year": 2024,
                "month": 6,
                "amount": 6541431.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 251,
                "shop_id": 3,
                "shop_account_title_id": 22,
                "year": 2024,
                "month": 6,
                "amount": 6276723.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 252,
                "shop_id": 3,
                "shop_account_title_id": 23,
                "year": 2024,
                "month": 6,
                "amount": 6125509.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 253,
                "shop_id": 3,
                "shop_account_title_id": 24,
                "year": 2024,
                "month": 6,
                "amount": 6708342.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 254,
                "shop_id": 3,
                "shop_account_title_id": 20,
                "year": 2024,
                "month": 12,
                "amount": 12890940.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 255,
                "shop_id": 3,
                "shop_account_title_id": 21,
                "year": 2024,
                "month": 12,
                "amount": 12676590.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 256,
                "shop_id": 3,
                "shop_account_title_id": 22,
                "year": 2024,
                "month": 12,
                "amount": 12651232.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 257,
                "shop_id": 3,
                "shop_account_title_id": 23,
                "year": 2024,
                "month": 12,
                "amount": 12573952.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 258,
                "shop_id": 3,
                "shop_account_title_id": 24,
                "year": 2024,
                "month": 12,
                "amount": 13063696.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 259,
                "shop_id": 3,
                "shop_account_title_id": 25,
                "year": 2022,
                "month": 6,
                "amount": 1633146.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 260,
                "shop_id": 3,
                "shop_account_title_id": 26,
                "year": 2022,
                "month": 6,
                "amount": 1637448.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 261,
                "shop_id": 3,
                "shop_account_title_id": 27,
                "year": 2022,
                "month": 6,
                "amount": 1596037.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 262,
                "shop_id": 3,
                "shop_account_title_id": 28,
                "year": 2022,
                "month": 6,
                "amount": 1622945.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 263,
                "shop_id": 3,
                "shop_account_title_id": 29,
                "year": 2022,
                "month": 6,
                "amount": 1682875.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 264,
                "shop_id": 3,
                "shop_account_title_id": 25,
                "year": 2022,
                "month": 12,
                "amount": 3308466.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 265,
                "shop_id": 3,
                "shop_account_title_id": 26,
                "year": 2022,
                "month": 12,
                "amount": 3366848.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 266,
                "shop_id": 3,
                "shop_account_title_id": 27,
                "year": 2022,
                "month": 12,
                "amount": 3246585.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 267,
                "shop_id": 3,
                "shop_account_title_id": 28,
                "year": 2022,
                "month": 12,
                "amount": 3237852.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 268,
                "shop_id": 3,
                "shop_account_title_id": 29,
                "year": 2022,
                "month": 12,
                "amount": 3356662.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 269,
                "shop_id": 3,
                "shop_account_title_id": 25,
                "year": 2023,
                "month": 6,
                "amount": 1615198.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 270,
                "shop_id": 3,
                "shop_account_title_id": 26,
                "year": 2023,
                "month": 6,
                "amount": 1621324.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 271,
                "shop_id": 3,
                "shop_account_title_id": 27,
                "year": 2023,
                "month": 6,
                "amount": 1640206.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 272,
                "shop_id": 3,
                "shop_account_title_id": 28,
                "year": 2023,
                "month": 6,
                "amount": 1670436.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 273,
                "shop_id": 3,
                "shop_account_title_id": 29,
                "year": 2023,
                "month": 6,
                "amount": 1605930.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 274,
                "shop_id": 3,
                "shop_account_title_id": 25,
                "year": 2023,
                "month": 12,
                "amount": 3288718.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 275,
                "shop_id": 3,
                "shop_account_title_id": 26,
                "year": 2023,
                "month": 12,
                "amount": 3417562.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 276,
                "shop_id": 3,
                "shop_account_title_id": 27,
                "year": 2023,
                "month": 12,
                "amount": 3350769.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 277,
                "shop_id": 3,
                "shop_account_title_id": 28,
                "year": 2023,
                "month": 12,
                "amount": 3314760.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 278,
                "shop_id": 3,
                "shop_account_title_id": 29,
                "year": 2023,
                "month": 12,
                "amount": 3293919.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 279,
                "shop_id": 3,
                "shop_account_title_id": 25,
                "year": 2024,
                "month": 6,
                "amount": 1691231.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 280,
                "shop_id": 3,
                "shop_account_title_id": 26,
                "year": 2024,
                "month": 6,
                "amount": 1707130.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 281,
                "shop_id": 3,
                "shop_account_title_id": 27,
                "year": 2024,
                "month": 6,
                "amount": 1733898.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 282,
                "shop_id": 3,
                "shop_account_title_id": 28,
                "year": 2024,
                "month": 6,
                "amount": 1604432.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 283,
                "shop_id": 3,
                "shop_account_title_id": 29,
                "year": 2024,
                "month": 6,
                "amount": 1587191.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 284,
                "shop_id": 3,
                "shop_account_title_id": 25,
                "year": 2024,
                "month": 12,
                "amount": 3340751.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 285,
                "shop_id": 3,
                "shop_account_title_id": 26,
                "year": 2024,
                "month": 12,
                "amount": 3343081.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 286,
                "shop_id": 3,
                "shop_account_title_id": 27,
                "year": 2024,
                "month": 12,
                "amount": 3394495.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 287,
                "shop_id": 3,
                "shop_account_title_id": 28,
                "year": 2024,
                "month": 12,
                "amount": 3246287.00,
                "created_at": now,
                "updated_at": now
            },
            {
                "id": 288,
                "shop_id": 3,
                "shop_account_title_id": 29,
                "year": 2024,
                "month": 12,
                "amount": 3234833.00,
                "created_at": now,
                "updated_at": now
            },
        ]
    )


